### ISSUE TITLE
Git branch push info is not showing

### ISSUE THREAD

**Issue by weilinzung** [olivierverdier/zsh-git-prompt#129]
Hi,
If the branch is ` upstream` then the prompt info would not show the push arrow when I have un-push commits. 

Only the check mark shows, after `git push --set-upstream` then everything would be normal.

screenshot: http://i.imgur.com/tKXu7Iq.png

thanks!

**Comment by Felixoid** [comment]
@weilinzung this repo is abandoned, look to https://github.com/starcraftman/zsh-git-prompt
