### ISSUE TITLE
git_super_status appears twice on cli

### ISSUE THREAD

**Issue by jcarpenter12** [olivierverdier/zsh-git-prompt#146]
Hi all,

I'm not sure if this may be default behaviour or not but the git_super_status prompt appears twice in my terminal when using it. Once at the start of the line and then again at the end, like so

```
➜  my_repo (master|✔)                                                                                                                                                           (master✔)  
```  
my theme config looks like
```
PROMPT="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_super_status) '
```

Does anyone know how I can change this so that it only appears once in the terminal?

**Comment by thomasrebele** [comment]
The right part of the prompt is defined by the $RPROMPT env variable. Could you check it?

**Comment by jcarpenter12** [comment]
Apologies for the confusion, I was using the git-prompt plugin included with oh-my-zsh. The RPROMPT is set by default at the end of the script 

https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/git-prompt/git-prompt.plugin.zsh

Closing issue
