### ISSUE TITLE
Symbol to distinguish untracked local branch 

### ISSUE THREAD

**Issue by tringuyen-yw** [olivierverdier/zsh-git-prompt#147]
Hi,

This might be not an issue, because I am not yet familiar with all the fine config of `zsh-git-prompt`. Is there a way to tell if a branch is not yet pushed to remote?

```
git ch -b MyNewBranch
echo "Hello" > hello.txt
git commit -am "add new file"
```

The prompt would look like `(MyNewBranch|✔)` which hints that the branch in sync with remote. In fact this branch is only local, untracked and not yet pushed to remote. 

Would it be OK to make another symbol for untracked branch? Like a red checkmark?

**Comment by thomasrebele** [comment]
The original repository is not maintained anymore.
Using the new fork (https://github.com/zsh-git-prompt/zsh-git-prompt) it should appear as [MyNewBranch L|…1]. Otherwise you can create an issue there.

**Comment by tringuyen-yw** [comment]
Thanks very much @thomasrebele for directing me to the new fork. The issue is indeed fixed in the new fork.
