### ISSUE TITLE
Maintain zsh-git-prompt by new community.

### ISSUE THREAD

**Issue by buko106** [olivierverdier/zsh-git-prompt#155]
This repository dose not seem to be maintained. We(users) should fork this project.

- requirements
  - When new OS, zsh, and others update launched, maintain code as it runs in a new environment.
  - Deliver new versions via package managers (homebrew and so on.)

**Comment by buko106** [comment]
There is no more feature required. I'm satisfied with current behavior.

**Comment by thomasrebele** [comment]
You're welcome to join https://github.com/zsh-git-prompt/zsh-git-prompt.

**Comment by buko106** [comment]
Thanks for immediate reply.
I could remove [this workaround](https://github.com/olivierverdier/zsh-git-prompt/issues/153)

**Comment by thomasrebele** [comment]
The fork has changed substantially, so removing the workaround might not be necessary anymore. I don't have Mac OS, so I cannot check. Feel free to make a PR.

**Comment by buko106** [comment]
new community is [here](https://github.com/zsh-git-prompt/zsh-git-prompt), so close this issue.
