### ISSUE TITLE
Carriage Returns on Windows

### ISSUE THREAD

**Issue by sigma914** [olivierverdier/zsh-git-prompt#51]
On windows the haskell implementation spits out windows newlines ie crlf.

This breaks zsh when it tries to compare against what it expects to be ints.

The haskell impl could use putStr and manually output a linefeed, another seperator character could be used or zshrc.sh could manually strip whitespace (this is the hack I'm currently running).

**Comment by olivierverdier** [comment]
Thanks a lot for reporting this! That's a very serious bug. I'll find a workaround as soon as possible.

**Comment by olivierverdier** [comment]
As I know use spaces to separate the bits of information, the problem should be solved (at least in fc116c91689bc86c5c1a88007490c917c7dbe079). Feel free to reopen if the problem persists. Thanks again for reporting this issue.

**Comment by sigma914** [comment]
That almost fixed it, unfortunately the single trailing newline from putStrLn (main.hs:37) still causes an issue.

Replacing it with putStr makes everything work perfectly.

Thanks for the fast response and fix!

**Comment by olivierverdier** [comment]
I see. I don't quite understand why it would cause a problem (as the trailing newline does not cause a problem in other systems for zsh), but as your suggested change seems harmless, I'll apply it. Thanks again!

**Comment by sigma914** [comment]
It seems to be something to do with zsh's handling of the carriage return, it's correctly stripping off the LF from the end but the CR is being treated as part of the final integer which then produces a type error from zsh.

It's probably the cygwin zsh (which expects unix conventions everywhere) not playing nice with the mingw GHC (which seems to use windows conventions for everything). I'm not really sure where the "blame" lies, it's just one of those annoying windows niggles.

Thanks!

**Comment by olivierverdier** [comment]
> It's probably the cygwin zsh (which expects unix conventions everywhere) not playing nice with the mingw GHC (which seems to use windows conventions for everything).

Ah, yes, that makes sense.

**Comment by olivierverdier** [comment]
The problem should now be fixed in 9f0da67e1e816748cd06aebc3db3de00a8f9b57e
