### ISSUE TITLE
Prompt only updates when zsh is first started

### ISSUE THREAD

**Issue by zhimsel** [olivierverdier/zsh-git-prompt#53]
If I make changes or cd into a git repository, zsh does not register the difference (e.g. the changed files, or the fact that we're now in a git repo) until you launch `zsh` again.

For example, starting in a regular directory (/), then `cd`ing into a git repo ($HOME):
```
USER at HOST in  /
$ cd ~
USER at HOST in  ~
$ zsh
USER at HOST in  ~  (master↑2|✚2)
$
```

The same thing happens when you are already in a git repo, and changes are made:
```
USER at HOST in  ~/test  (master|✔)
$ touch test
USER at HOST in  ~/test  (master|✔)
$ zsh
USER at HOST in  ~/test  (master|…)
$ git add test
USER at HOST in  ~/test  (master|…)
$ zsh
USER at HOST in  ~/test  (master|●1)
$
```

I'm unsure if it's related, but the stock zsh `${git_branch}` doesn't register changes for me. It only shows the branch. On some machines it works (all have the same exact config files), on others it doesn't.

Let me know if you need any config files, or environment variables, etc.

My `.zshrc` at the time of testing (prompt starts at line 33): https://github.com/zhimsel/dotfiles/blob/af3687d409e5bac1eb1c735076eaa79c2b7f0806/.zshrc

**Comment by cevaris** [comment]
+1 Getting the same issue here. The `git` prompt is not updating whent changing directories.

**Comment by zhimsel** [comment]
Does it also not update for changes in the git status? (e.g. added a new file, or there are new unstaged changes) For me, it only displays what was present at the time zsh launched.

**Comment by cevaris** [comment]
The `__CURRENT_GIT_STATUS` status does get updated properly on change of directory. Thought there is nothing invoking `git_super_status` to update the current `PROMPT` variable. The following manual updating of PROMP works for me.

In my **.zshrc** file
```
# Prompt
# Git
source ~/.zsh.d/zsh-git-prompt/zshrc.sh
PROMPT="%{$fg[green]%}%c $(git_super_status)%{$fg[red]%}~%{$fg[white]%}࿔ %{$reset_color%}"

autoload -U add-zsh-hook
add-zsh-hook chpwd update_prompt
function update_prompt() {
    PROMPT="%{$fg[green]%}%c $(git_super_status)%{$fg[red]%}~%{$fg[white]%}࿔ %{$reset_color%}"
}
```

**Comment by zhimsel** [comment]
Hm. I'll have to try that later. Thanks.

**Comment by klaasb** [comment]
I think the same thing applies here, as in the other issue: https://github.com/olivierverdier/zsh-git-prompt/issues/55#issuecomment-77440662

**Comment by zhimsel** [comment]
@cevaris Your solution works, but only for when you change directories. If you stay in the same dir and just update git somehow (checking out a different branch, making commit, etc), the status is not reflected until you `cd .`.

**Comment by zhimsel** [comment]
Workaround in #55 (thanks @cevaris )

**Comment by zhimsel** [comment]
Closing issue (workaround in #55)
