### ISSUE TITLE
Add a symbolic link to let it work as oh-my-zsh plugin out of the box

### ISSUE THREAD

**Issue by sirblackheart** [olivierverdier/zsh-git-prompt#69]
Hi,
i know that there is already a oh-my-zsh plugin version of zsh-git-prompt, but it does not come with the haskell version and i do not know how much of the updates they have integrated. So i  prefer to use this version.
By adding a symbolic link zsh-git-prompt.plugin.zsh -> zshrc.sh people can just clone this into their custom plugin folder and it works as oh-my-zsh plugin without further work.

**Comment by olivierverdier** [comment]
Good point, I'm using oh-my-zsh myself. I should add some instructions in the Readme.

What I do is that I have an oh-my-zsh plugin which is just a symlink of the `zshrc.sh` in this repo. Feel free to reopen this issue if you have further questions.
