### ISSUE TITLE
add `dist` directory to `.gitignore`

### ISSUE THREAD

**Issue by fin-8** [olivierverdier/zsh-git-prompt#72]
When compiling the Haskell version, the binaries are being placed in the `dist` directory, leaving the repository "dirty".
By adding the `dist` directory to `.gitignore`, one could use this repo more easily in a custom _dotfiles_ repository as a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

**Comment by zhimsel** [comment]
Already proposed in #61
