### ISSUE TITLE
Remote commits is not working

### ISSUE THREAD

**Issue by mevouc** [olivierverdier/zsh-git-prompt#78]
Me and several of my friends have an issue with the prompting of the remote commits (the downward arrow). It's simply never visible, like if our computer doesn't detect remote commits.
Is there a particular thing to config ?
The other symbols work fine.

**Comment by olivierverdier** [comment]
The down arrow will only appear if the tracked remote is ahead of you. If there is no down arrow, while the word `behind` appears in the result of `git status -sb`, then please submit a bug report immediately.

**Comment by mevouc** [comment]
Well apparently it's more an issue with my git install, rather than with your git prompt. Even when the remote is ahead of me, `git status -sb` works like if I was up-to-date with the remote branch.
Sorry for the inconvenience.
