### ISSUE TITLE
git_super_status problem

### ISSUE THREAD

**Issue by Frulenzo** [olivierverdier/zsh-git-prompt#85]
I always get this type of error :

``` sh
zsh: command not found: git_super_status 
```

Can somebody point a quick solution for this?
By the way it is really nice zsh theme because I really want this _current branch_ view :)
Kudos to author!

Best regards,
Hrvoje

**Comment by olivierverdier** [comment]
You have to include "source ...zshrc.sh" as indicated in the readme, this is where `git_super_status` is defined. Difficult to help you without more information. Also, you are more likely to get help using stackoverflow instead of github issues.

**Comment by Frulenzo** [comment]
I already done that what you said but still this problem occurs. Oh well, I will do more research on Stackoverflow then :)

**Comment by talwrii** [comment]
I was installined with [zplug](https://github.com/zplug/zplug).

I added the following to my zshrc to get this working.

```source $ZPLUG_HOME/repos/olivierverdier/zsh-git-prompt/zshrc.sh```
