### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by alyssais** [olivierverdier/zsh-git-prompt#89]
Noticed that there hasn't been a release on GitHub for several years. Would be useful if they were more frequent because it would allow zsh-git-prompt to be installed with package managers. Will there be a new release any time soon? Is there a need for one?

**Comment by olivierverdier** [comment]
Good point, the current version is pretty stable. I'll make a release out of it. Is that what you had in mind?

**Comment by alyssais** [comment]
Yeah, thanks!

**Comment by olivierverdier** [comment]
I made a new release from the current version.
